---
- name: set up laptop
  hosts: localhost
  connection: local
  sudo: yes
  tasks:
  - name: add java repo
    sudo: yes
    apt_repository: repo='ppa:webupd8team/java' state=present
    register: result
    tags:
    - java

  - name: Select Oracle License
    sudo: yes
    shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
    when: result.changed
    tags:
    - java

  - name: Install JRE
    sudo: yes
    apt: name=oracle-java8-installer state=latest update-cache=yes
    tags:
    - java

  - name: install software
    apt: update_cache=yes name={{item}} state=latest
    with_items:
    - python
    - python-apt
    - git
    - build-essential
    - openssh-server
    - zsh
    - ansible
    - terminator
    - aptitude
    - android-tools*
    - s3cmd
    - mosh
    - gparted
    - p7zip
    - numlockx

  - name: enable numlock on boot
    lineinfile:
      dest: /etc/X11/xinit/xinitrc
      line: "/usr/bin/numlockx on"
      regexp: "^/usr/bin/numlockx "

  - name: apply updates
    apt: upgrade=yes update_cache=yes

  - name: remove software
    apt: name={{item}} state=absent
    with_items:
    - pinta
    - imagemagick

  - name: copy zsh files
    sudo: no
    synchronize: src=files/ dest=~/ recursive=yes

  - name: change default terminal to terminator
    shell: "gsettings set org.gnome.desktop.default-applications.terminal exec 'terminator'"
