---
- name: set up laptop
  hosts: localhost
  connection: local
  become: yes
  tasks:
  - name: install software
    apt: update_cache=yes name={{item}} state=latest
    with_items:
    - python
    - python-apt
    - git
    - build-essential
    - zsh
    - aptitude
    - mosh
    - p7zip

  - name: install software
    apt: update_cache=yes name={{item}} state=latest
    with_items:
    - terminator
    - android-tools*
    - numlockx
    tags:
    - gui

  - name: enable numlock on boot
    lineinfile:
      dest: /etc/X11/xinit/xinitrc
      line: "/usr/bin/numlockx on"
      regexp: "^/usr/bin/numlockx "
    tags:
    - gui

  - name: apply updates
    apt: upgrade=yes update_cache=yes

  - name: copy files
    become: no
    synchronize: src=files/ dest=~/ recursive=yes
    tags:
    - zsh

  - name: setup ansible log file
    become: yes
    file: path=/var/log/ansible.log state=touch mode=666

  - name: change default terminal to terminator
    shell: "gsettings set org.gnome.desktop.default-applications.terminal exec 'terminator'"
    tags:
    - gui
